### ISSUE TITLE
snapcraft pack error obtuse on snapd errors

### ISSUE THREAD

**Issue by sergiusens** [canonical/snapcraft#4870] opened 2024-06-23 15:35 UTC
### Bug Description

The messages are being hidden from snap pack, this seems to be a core24 regression

### To Reproduce

pack a snap on core24 with a command to a path that does not exist

### Environment

core24

### snapcraft.yaml

```shell
name: apostrophe
base: core24
adopt-info: apostrophe

grade: devel
confinement: devmode

apps:
  apostrophe:
    command: bin/apostrophe
    extensions: [gnome]

build-packages:
  - pandoc

parts:
  apostrophe:
    source: https://gitlab.gnome.org/World/apostrophe.git
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    parse-info:
      - usr/share/metainfo/org.gnome.gitlab.somas.Apostrophe.metainfo.xml 
    after:
      - revealjs
  revealjs:
    source: https://github.com/hakimel/reveal.js/archive/refs/tags/5.1.0.tar.gz
    plugin: dump
    organize:
      "*": usr/share/apostrophe/libs/reveal.js/
```

### Relevant log output

```shell
Command '['snap', 'pack', '--filename', 'apostrophe_3.0_amd64.snap', '--compression', 'xz', PosixPath('/root/prime'), PosixPath('/root/project')]' returned non-zero exit status 1.           
snapcraft-apostrophe-on-amd64-for-amd64-21764214 ../project# cat ../prime/meta/snap.yaml
```

### Additional context

Manual snap pack on the prime dir
```
2024/06/23 12:32:30.262115 container.go:393: in snap "apostrophe": path "bin/apostrophe" does not exist
2024/06/23 12:32:30.262192 container.go:393: in snap "apostrophe": path "bin" does not exist
error: cannot pack "../prime": snap is unusable due to missing files
```

**Comment by mr-cal** [comment] 2024-06-24 12:10
Closing as a duplicate of https://github.com/canonical/snapcraft/issues/4548.  This also occurs in core22.

**Closed by mr-cal** 2024-06-24 12:10 UTC
